name: Load testing 3

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-dev.yml up -d
    - run: sleep 40
    - name: Load test
      run: |
        git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2024-q1.git
        cd rinha-de-backend-2024-q1
        wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.10.3/gatling-charts-highcharts-bundle-3.10.3-bundle.zip
        mkdir gatling/3.10.3 -p
        unzip gatling-charts-highcharts-bundle-3.10.3-bundle.zip
        mv gatling-charts-highcharts-bundle-3.10.3/* gatling/3.10.3/
        ./executar-teste-local.sh
        echo GATLING_OUTPUT_FOLDER=$(ls $HOME/load-test/user-files/results | sort | head -n 1) >> $GITHUB_ENV
      env:
        WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2024-q1/load-test
        HOME: ${{ github.workspace }}/rinha-de-backend-2024-q1
        url: ${{ steps.deployment.outputs.page_url }}
    - run: docker-compose ps
    - run: docker-compose logs
      # Single deploy job since we're just deploying
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/rinha-de-backend-2024-q1/load-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
        keep_files: true
        destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
    - run: echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
    - run: echo "[Deploying to https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"
      uses: mshick/add-pr-comment@v2
        with:
          message: |
            Test 03 result: [https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }})